sudo: required

language: node_js
node_js:
  - 14

services:
  - docker
  # - mongodb 

before-install: 
  - docker run mongo
script:  
  - mocha tests.js --timeout 5000

after_success:
  - docker build -t goodbuy/nodejs-webserver:travis .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push goodbuy/nodejs-webserver:travis