sudo: required

language: node_js
node_js:
  - 14

services:
  - docker
  - mongodb


script:
  - sleep 15
  - npx tsc
  - mocha tests.js --timeout 5000

after_success:
  - docker build -t goodbuy/nodejs-webserver:travis .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push goodbuy/nodejs-webserver:travis

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: docker-loginapp
  env: Dockerloginapp-env
  bucket_name: elasticbeanstalk-eu-central-1-861910211422
  bucket_path: docker-loginapp
  on:
    branch: enhancement/local_without_docker
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
