sudo: required

services:
  - docker 

before-install: 
  - docker build -t goodbuy/nodejs-webserver:dev .

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push goodbuy/nodejs-webserver:dev
  
