sudo: required

language: node_js
node_js:
  - 14

services:
  - docker
  - mongodb 

# before-install: 
env:
  - RABBITMQ_DEV_HOST="18.194.28.180"
  - RABBITMQ_PORT="5672"
  - RABBITMQ_USER="guest"
  - RABBITMQ_USER_PW="guest"
  - MONGODB_DEV_URI="mongodb+srv://dev-backend:NBiLdPhQWAxqO4PK@dev-db-goodbuy.0iqtx.mongodb.net/dev?retryWrites=true&w=majority"

script:  
  - sleep 15
  - npx tsc
  - mocha tests.js --timeout 5000

after_success:
  - docker build -t goodbuy/nodejs-webserver:travis .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push goodbuy/nodejs-webserver:travis