version: "2"
services:
  backend:
    environment:
      - NODE_ENV=dev
    container_name: server
    image: login
    ports:
      - "80:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "node dist/server.js"
