version: "2"
services:
  backend:
    environment:
      - DBHost=$DBHost
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_USER_PW=$RABBITMQ_USER_PW
      - RABBITMQ_DEV_HOST=$RABBITMQ_DEV_HOST
      - RABBITMQ_PORT=$RABBITMQ_PORT    
      container_name: server
    image: goodbuy/nodejs-webserver:dev
    ports:
      - "80:8080"
    command: "node dist/server.js"
