services:
  backend:
    environment:
      - NODE_ENV=test
    depends_on:
      - mongodb
    command: "nodemon server.js"
  mongodb:
    container_name: goodbuy_database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: "--logpath=/dev/null"
