version: "2"
services:
  backend:
    environment:
      - NODE_ENV=dev
    container_name: server
    image: goodbuy/nodejs-webserver:dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "nodemon server.js"
