version: "2"
services:
  backend:
    environment:
      - ACCESS_TOKEN_SECRET="$ACCESS_TOKEN_SECRET"
      - DBHost=$DBHost
      - MONGODB_DEV_URI=$MONGODB_DEV_URI
      - RABBITMQ_DEV_HOST=$RABBITMQ_DEV_HOST
      - RABBITMQ_PORT=$RABBITMQ_PORT
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_USER_PW=$RABBITMQ_USER_PW
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - EMAIL_CONFIRMATION_SECRET=$EMAIL_CONFIRMATION_SECRET
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASS=$EMAIL_PASS
    container_name: server
    image: goodbuy/nodejs-webserver:dev
    ports:
      - "80:8080"
    command: "node dist/server.js"
