version: "2"
services:
  backend:
    environment:
      - NODE_ENV=dev
    container_name: server
    image: goodbuy/nodejs-webserver:prometheus
    ports:
      - "80:8080"
    command: "node dist/server.js"
