services:
  backend:
    depends_on:
      - mongodb
    command: "npm run test"
  mongodb:
    container_name: goodbuy_database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: "--logpath=/dev/null"
