version: "2"
services:
  backend:
    container_name: server
    image: goodbuy-nodejs-image
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run dev"
